apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: web-prod
  name: github-deployer-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: web-prod
  name: github-deployer-binding
subjects:
  - kind: User
    name: github-actions-deployer
roleRef:
  kind: Role
  name: github-deployer-role
  apiGroup: rbac.authorization.k8s.io
